added test harness and nginx image to run it; also fixed some bugs and cleaned up validation

diff --git a/bin/test-integration b/bin/test-integration
--- a/bin/test-integration
+++ b/bin/test-integration
@@ -5,24 +5,24 @@ echo "testing integration"
 : ${US_SERVER_HOST:=localhost}
 : ${US_SERVER_PORT:=3000}
 
-for i in `seq 0 20`; do
-  hc=(curl -i "${US_SERVER_HOST}:${US_SERVER_PORT}/hc")
+# for i in `seq 0 20`; do
+#   hc=(curl -i "${US_SERVER_HOST}:${US_SERVER_PORT}/hc")
 
-  echo -n "${hc[@]} "
+#   echo -n "${hc[@]} "
 
-  if ${hc[@]} 2>/dev/null; then 
-    echo
-    echo "successful healthcheck"
-    break
-  elif [ "$i" -eq 20 ]; then 
-    echo "failed after 21 retries, giving up"
-    exit 1
-  else
-    echo "healthcheck failed, retrying: $i"
-  fi
+#   if ${hc[@]} 2>/dev/null; then 
+#     echo
+#     echo "successful healthcheck"
+#     break
+#   elif [ "$i" -eq 20 ]; then 
+#     echo "failed after 21 retries, giving up"
+#     exit 1
+#   else
+#     echo "healthcheck failed, retrying: $i"
+#   fi
   
-  sleep 1s
-done
+#   sleep 1s
+# done
 
 cd tests && go mod vendor && go clean -testcache 
 
